blag/blueprint.py
import datetime

import os

from google.appengine.ext import ndb
import flask
from blag.utils import make_memcache_key_for_blag, make_memcache_key
from blag_gae_helpers import object_or_404, make_memcache_key_for_user, get_from_memcache
from flask import Blueprint, render_template, abort, g, redirect, current_app
from flask.helpers import url_for

from auth import login_utils
from auth import models as login_models

from . import models, forms, utils


CURRENT_DIR = os.path.split(os.path.abspath(__file__))[0]

blag = Blueprint(
  'blag', __name__,
  template_folder=os.path.join(CURRENT_DIR, "templates")
)

@blag.route('/add', methods=['GET', 'POST'])
@login_utils.require_login
def add_blag():
  form = forms.AddBlagForm()
  if form.validate_on_submit():
    blag = form.save_blag(login_utils.current_user())
    return redirect(url_for("blag.add_post", blag_key=blag.key.urlsafe()))
  return render_template(
    "markdown_form.html",
    page_title="Add Blog",
    form=form,
    edited_object_key="blag_description"
  )


def __add_or_edit_post(blag_key, post=None):
  blag_key = ndb.Key(urlsafe=blag_key)
  blag = blag_key.get()
  if login_utils.current_user().key not in blag.owners:
    abort(403)
  if blag is None:
    flask.abort(404)
  form = forms.AddBlagPost(obj=post)
  if form.validate_on_submit():
    post = form.save_post(blag, login_utils.current_user())
    return redirect(url_for("blag.post_detail", post_key=post.key.urlsafe()))
  return render_template(
    "markdown_form.html",
    page_title="Add Blog Post",
    form=form,
    edited_object_key = post.key if post is not None else "new_post"
  )


@blag.route("/addpost/<blag_key>", methods=['GET', 'POST'])
@login_utils.require_login
def add_post(blag_key):
  return __add_or_edit_post(blag_key)


@blag.route("/post/edit/<post_key>", methods=['GET', 'POST'])
@login_utils.require_login
def edit_post(post_key):
  post_key = ndb.Key(urlsafe=post_key)
  post = post_key.get()
  if post is None:
    flask.abort(404)
  return __add_or_edit_post(post.blag.urlsafe(), post)


@blag.route("/view/<post_key>", methods=['GET'])
def post_detail(post_key):
  post_key = ndb.Key(urlsafe=post_key)
  post = post_key.get()
  return render_template(
    "blag_post.html",
    post=post,
    blag=post.blag.get()
  )


def do_pagination(offset, posts_to_load, query, cache_key):
  context = {}

  results, cursor, more = get_from_memcache(
    cache_key, lambda: query.fetch_page(posts_to_load, offset=offset),
    expiration_sec=600
  )

  previous_offset = offset - posts_to_load

  if previous_offset > 0:
    context['prev_url'] = "?start_from={}&posts={}".format(
      previous_offset, posts_to_load
    )

  if more:
    context['next_url'] = "?start_from={}&posts={}".format(
      offset + posts_to_load, posts_to_load
    )

  return results, context


@blag.route("/list/<blag_key>", methods=['GET'])
@blag.route("/list/<blag_key>/<year>/<month>", methods=['GET'])
def blag_view(blag_key, year=None, month=None):
  try:
    if year is not None and month is not None:
      year = int(year)
      month = int(month)
  except ValueError:
    flask.abort(400)

  blag = object_or_404(blag_key)
  posts = models.BlagPost.query(models.BlagPost.blag == blag.key).order(
    -models.BlagPost.create_date
  )
  if year is not None and month is not None:
    end_date = datetime.datetime.combine(
      datetime.date(year=year, month=month+1, day=1),
      datetime.time()
    )
    start_date = datetime.datetime.combine(
      datetime.date(year=year, month=month, day=1),
      datetime.time()
    )
    posts = posts.filter(
      models.BlagPost.create_date >= start_date,
      models.BlagPost.create_date < end_date,
    )

  form = forms.BlagPagination(formdata=flask.request.args, csrf_enabled=False)

  if not form.validate():
    flask.abort(400)

  cache_key = make_memcache_key_for_blag(
    blag, "post_list", form.data['start_from'], form.data['posts'],
    year, month
  )

  posts, context = do_pagination(
    offset=form.data['start_from'],
    posts_to_load=form.data['posts'],
    query=posts,
    cache_key=cache_key
  )

  return render_template(
    "blag_listing.html",
    blag=blag,
    posts=posts,
    blag_stats=blag.get_stats(),
    **context
  )


@blag.route("/list/tag/<tag>", methods=['GET'])
def blag_view_tag(tag):
  form = forms.BlagPagination(formdata=flask.request.args, csrf_enabled=False)
  if not form.validate():
    flask.abort(400)
  posts = models.BlagPost.query(models.BlagPost.tags == tag).order(
    -models.BlagPost.create_date
  )
  cache_key = make_memcache_key("post_by_tag", tag, form.data['start_from'], form.data['posts'])

  posts, context = do_pagination(
    offset=form.data['start_from'],
    posts_to_load=form.data['posts'],
    query=posts,
    cache_key=cache_key
  )

  return render_template(
    "post_list_by_tag.html",
    posts=posts,
    tag=tag,
    **context
  )


@blag.route("/list/author/<author>", methods=['GET'])
def blag_view_author(author):
  author_user = None
  try:
    author_user = login_models.User.get_by_username(username=author)
  except login_models.UserDoesNotExist:
    abort(404)
  form = forms.BlagPagination(formdata=flask.request.args, csrf_enabled=False)
  if not form.validate():
    flask.abort(400)
  posts = models.BlagPost.query(models.BlagPost.authors == author_user.key).order(
    -models.BlagPost.create_date
  )
  cache_key = make_memcache_key("post_by_author", author_user.key, form.data['start_from'], form.data['posts'])

  posts, context = do_pagination(
    offset=form.data['start_from'],
    posts_to_load=form.data['posts'],
    query=posts,
    cache_key=cache_key
  )

  return render_template(
    "post_list_by_author.html",
    posts=posts,
    author=author_user,
    **context
  )


def __is_blag_owner(blag):
  if not login_utils.is_logged_in():
    return False
  if not isinstance(blag, models.Blag):
    blag = blag.get()
  return login_utils.current_user().key in blag.owners


def update_context_logged_in():

  if not login_utils.is_logged_in():
    return {
      "blag_owner": __is_blag_owner,
    }
  return {
    "user_blags": utils.get_user_blags(),
    "blag_owner": __is_blag_owner,
  }

templates/base.html
{% import "bootstrap/wtf.html" as wtf %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="Jacek Bzdak">
{#    <link rel="icon" href="../../favicon.ico">#}

    <title>{% block title %}Blog{% endblock title %}</title>

    {% block styles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="{{ config.STATIC_URL }}css/vendor/blog.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block styles_extra %} {% endblock styles_extra%}
    {% endblock styles %}
  </head>

  <body>
    {% block body %}
    {% block nav %}
        {% include "navbar.html" %}
    {% endblock nav %}

    <div class="container">

      {% block header %}
      <div class="blog-header">
        <h1 class="blog-title">A simple Blog Engine</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
      </div>
      {% endblock %}
      {% block contents %}
      <div class="row">
        <div class="col-sm-8 blog-main">

          {% block main_column %}
              A list of blogs will be here someday.
          {% endblock main_column %}
        </div><!-- /.blog-main -->
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        {% block sidebar %}
        {% endblock sidebar %}
        </div><!-- /.blog-sidebar -->
      </div><!-- /.row -->
      {% endblock contents %}

    </div><!-- /.container -->

    <footer class="blog-footer">
      {% block footer %}
      <p>
        <a href="#">Back to top</a>
      </p>
      {% endblock footer %}
    </footer>

    {% endblock body %}

    {% block scripts_bottom %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="{{ STATIC_URL }}js/base.js"></script>
    {% block extra_scripts_bottom %}{% endblock extra_scripts_bottom %}
    {% endblock scripts_bottom %}
  </body>
</html>

templates/form.html
{% extends "simple.html" %}

{% block main_column %}
    {{ wtf.quick_form(form, method="POST") }}
{% endblock %}

{% block sidebar %}

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block main_column %}
  <p>Probably <small>not</small> the best blogging platform in
the world </p>
  <p>
    To start blogging register or login (link is at the top
    navbar).
  </p>
  <p>Just here to read: select blog from the sidebar!</p>


{% endblock %}
{% block sidebar %}
<div class="sidebar-module">
  <h4>Last updated blogs:</h4>
  <ul>
    {% for blag in blags %}
      <li><a
        href="{{ url_for("blag.blag_view", blag_key=blag.key.urlsafe() )}}"
        title="{{ blag.text_md }}"
        data-toggle="tooltip"

      >
        {{ blag.title }}
      </a> </li>
    {% else %}
      <li>Looks like there are no blogs, maybe
        <a href="{{ url_for("blag.add_blag") }}">create one?</a>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

templates/navbar.html
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <ul class="nav navbar-nav">
      {% block nav_pre %}
      <li><a class="blog-nav-item active" href="/">Home</a></li>
      {% endblock nav_pre %}
      {% block nav_extra %}

      {% endblock nav_extra %}
      {% block nav_login %}
      {% if user.is_anonymous %}
        <li><a class="blog-nav-item" href="{{ url_for("auth.login") }}">Login</a></li>
        <li><a class="blog-nav-item" href="{{ url_for("auth.register") }}">Register</a></li>
      {% else %}
        <li class="dropdown">
        <a href="#" class="blog-nav-item dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Your Blogs <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
        {% for blag in user_blags %}
            <li><a href="{{ url_for("blag.blag_view", blag_key=blag.key.urlsafe()) }}">{{ blag.title | truncate(15, True) }}</a> </li>
        {% else %}
            <li><p>Your blogs will be here.</p></li>
        {% endfor %}
        <li role="separator" class="divider"></li>
        <li><a href="{{ url_for("blag.add_blag") }}">Add Blog</a></li>
        </ul>
        </li>
      <li class="dropdown">
        <a href="#" class="blog-nav-item dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Your account <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a id="logout-link" class="blog-nav-item" href="{{ url_for("auth.logout") }}">Logout</a></li>
        </ul>
        </li>
      {% endif %}
      {% endblock %}
      </ul>
    </nav>
  </div>
</div>

templates/simple.html
{% extends "base.html" %}

{% block header %}
<div class="blog-header">
<h1 class="blog-title">{{ page_title }}</h1>
{% if page_description %}
<p class="lead blog-description">{{ page_description }}</p>
{% endif %}
</div>
{% endblock %}

{% block main_column %}
    {{ page_contents }}
{% endblock %}